rootProject.name = "Password generator"
include(":app")
include(":domain")
include(":data")
include(":cryptography")
include(":passwordvalidation")
include(":core:mvi")
include(":core:domain:base")
include(":core:domain:common")
include(":core:designsystem")
