package com.mateuszholik.passwordgenerator.models

enum class MessageType {
    DEFAULT_ERROR,
    PASSWORD_EDITION_ERROR,
    PASSWORD_GENERATION_ERROR,
    LOGIN_ERROR,
    CREATE_PIN_ERROR,
    VALIDATION_ERROR,
    DELETE_PASSWORD_ERROR,
    GET_PASSWORDS_ERROR,
    SAVE_PASSWORD_ERROR,
    SAVE_BIOMETRIC_AUTH_OPTION_ERROR,
    SAVE_PASSWORD_VALIDITY_OPTION_ERROR,
    GET_BIOMETRIC_AUTH_OPTION_ERROR,
    BIOMETRIC_AUTH_ERROR,
    BIOMETRIC_AUTH_FAILED,
    COPIED_TO_CLIPBOARD,
    LOGIN_WRONG_PIN_ERROR,
    CREATE_PIN_WRONG_PIN_ERROR,
    SAVE_PASSWORD_SUCCESS
}
