name: Android Build Pipeline

on: [pull_request]

jobs:
  build:
    name: Build, Test and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.2
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Setup Java JDK
        uses: actions/setup-java@v3.11.0
        with:
          distribution: 'zulu'
          java-version: '17'
      - name: Create google-services.json
        run: cat /home/runner/work/Passwordgenerator/Passwordgenerator/app/google-services.json | base64
      - name: Put data to google-services.json
        env:
          DATA: ${{ secrets.GOOGLE_SERVICES_JSON }}
        run: echo $DATA > /home/runner/work/Passwordgenerator/Passwordgenerator/app/google-services.json
      - name: Build
        run: ./gradlew :app:assembleDebug
      - name: Test
        run: ./gradlew :app:testDebugUnitTest :data:testDebugUnitTest :domain:testDebugUnitTest :passwordvalidation:testDebugUnitTest
